### ISSUE TITLE
"Invalid syntax" on Python 3.7.0

### ISSUE THREAD

**Issue by alanorth** [moonlitesolutions/SolrClient#79]
SolrClient 0.2.1 fails to run on Python 3.7.0:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from SolrClient import SolrClient
  File "/home/aorth/.local/share/virtualenvs/solr-pipenv-nV7koRrN/lib/python3.7/site-packages/SolrClient/__init__.py", line 1, in <module>
    from .solrclient import SolrClient
  File "/home/aorth/.local/share/virtualenvs/solr-pipenv-nV7koRrN/lib/python3.7/site-packages/SolrClient/solrclient.py", line 10, in <module>
    from .zk import ZK
  File "/home/aorth/.local/share/virtualenvs/solr-pipenv-nV7koRrN/lib/python3.7/site-packages/SolrClient/zk.py", line 9, in <module>
    from kazoo.client import KazooClient
  File "/home/aorth/.local/share/virtualenvs/solr-pipenv-nV7koRrN/lib/python3.7/site-packages/kazoo/client.py", line 62, in <module>
    from kazoo.recipe.partitioner import SetPartitioner
  File "/home/aorth/.local/share/virtualenvs/solr-pipenv-nV7koRrN/lib/python3.7/site-packages/kazoo/recipe/partitioner.py", line 193
    self._child_watching(self._allocate_transition, async=True)
                                                        ^
SyntaxError: invalid syntax
```

Virtual environment was created with pipenv.

**Comment by nickvasilyev** [comment]
Thanks for reporting, it looks like it is an issue with kazoo library, will
check it out this weekend.

**Comment by alanorth** [comment]
This is merely an issue with reserved words in Python 3.7. Kazoo 2.5.0 [removes the use of the `async` keyword and is compatible with Python 3.7](https://github.com/python-zk/kazoo/issues/455). I upgraded Kazoo to 2.5.0 in my environment and it works fine, though I'm only using SolrClient's query and facet functionality.

My environment is Linux with Python 3.7.

**Comment by verdan** [comment]
Guys, can we please fix this thing and release the new version ASAP ?
https://github.com/moonlitesolutions/SolrClient/pull/81

**Comment by nickvasilyev** [comment]
@verdan it should be good, I merged your PR and pushed the new version to PyPi. Thanks!

Can you pull it down and let me know if there are any other issues?

Thanks

**Comment by verdan** [comment]
Super!! that was quick @nickvasilyev. Thanks. 👍I will make sure to open a new PR if I find anything else.
